stages:
  - fuzzing
run_fuzz_tests:
  image: cifuzz/gitlab:v3
  stage: fuzzing
  variables:
    TIMEOUT: 300
    FINDINGS_TYPE: CRASH
    FUZZING_SERVER_URL: server-installer-test.code-intelligence.com:6773
    WEB_APP_ADDRESS: https://server-installer-test.code-intelligence.com
    # By default, the branch which the current CI job is running for is used
    # GIT_BRANCH: master
    PROJECT: projects/organizations_7eb9b18fc0064648_taocpp-json-api_git-5071b24a
  script:
    - CAMPAIGN_RUN=$(start_fuzzing.sh)
    - export CAMPAIGN_RUN
    - monitor_fuzzing.sh
