name: Code Intelligence Fuzzing

on:
  push:
    branches: [ master, fuzz-without-validator ]
  pull_request:
    branches: [ master, fuzz-without-validator ]

env:
  FUZZING_SERVER_ADDRESS: server-installer-test.code-intelligence.com:6773
  WEB_APP_ADDRESS:  https://server-installer-test.code-intelligence.com
  

jobs:       
  fuzz_msgpack_tovalue_without_validation:
    runs-on: ubuntu-latest
    steps:
      - id: start-fuzzing
        name: Build and Instrument
        uses: CodeIntelligenceTesting/github-actions/start-fuzzing@v3
        with:
          ci_fuzz_api_token: ${{ secrets.TEST_SERVER_CI_TOKEN }}
          test_collection: "projects/organizations_7eb9b18fc0064648_taocpp-json-api_git-5071b24a/campaigns/msgpack_tovalue_without_validation-5f04f5d9"
          git_reference: ${{ github.sha }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}          
      - id: monitor-fuzzing
        name: Fuzzing
        uses: CodeIntelligenceTesting/github-actions/monitor-fuzzing@v3
        with:
          ci_fuzz_api_token: ${{ secrets.TEST_SERVER_CI_TOKEN }}
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ github.event.pull_request.number }}
          owner: ${{ github.event.repository.owner.login }}
          repository: ${{ github.event.repository.name }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
          dashboard_address: ${{ env.WEB_APP_ADDRESS }}
      - id: report-coverage
        name: Report Coverage
        uses: CodeIntelligenceTesting/github-actions/report-coverage@v3
        if: ${{ github.event_name == 'pull_request' && (success() || failure()) }}
        with:
          ci_fuzz_api_token: ${{ secrets.TEST_SERVER_CI_TOKEN }}
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ github.event.pull_request.number }}
          owner: ${{ github.event.repository.owner.login }}
          repository: ${{ github.event.repository.name }}
          git_reference: ${{ github.sha }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
          dashboard_address: ${{ env.WEB_APP_ADDRESS }}
